version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      # Убедитесь, что порт 3001 соответствует порту, который вы указали в настройках Timeweb Cloud
      - "3001:3001"
    # Убран блок volumes
    environment:
      # Опционально: установка языка интерфейса
      - LANGUAGE=ru-RU
      # Опционально: установка часового пояса
      - TZ=Europe/Moscow

# Убран блок volumes
